name: PHP CodeSniffer

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - 8.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: PHPCS
        run: composer run-script phpcs
