name: PHPUnit

on:
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
          - 8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install wordpress environment
        run: npm -g install @wordpress/env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Setup the wordpress environment
        run: wp-env start

      - name: PHPUnit
        run: composer test --no-interaction

      - name: PHPUnit multisite
        run: composer run-script test-multisite --no-interaction
